---
title: "Carnival Imagination: AIS Data June 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[MMSI: 309933000](https://www.marinetraffic.com/en/ais/details/ships/shipid:370651/mmsi:309933000/imo:9053878/vessel:CARNIVAL_IMAGINATION)  
1-2 June 2019 
[View Cruise Itinerary](http://crew-center.com/carnival-imagination-itinerary)

```{r, echo=FALSE, message=FALSE}
#install.packages('devtools')
library(tidyverse)
library(devtools)
#devtools::install_github("mvisalli/shipr")
library(shipr)
library(leaflet)
library(sf)
library(dplyr)
library(lubridate)
library(readr)


sbais_ci<-readRDS("data/sbais_ci.RDS") %>% 
  arrange(datetime) %>%
  filter(!duplicated(round_date(datetime, unit="minute"))) %>% 
  st_as_sf(coords=c("lon","lat"), crs = 4326)

bins_ci <- c(0,10,11,12,15,20)

pal_ci <- colorBin( "YlOrRd",
                    domain= sbais_ci$speed,
                    bins = bins_ci,
                    na.color = 'black')

map_ci <- leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data=sbais_ci,
                   radius = 0.5,
                   label = ~sprintf("%f knots - %s",speed,datetime),
                   color=~pal_ci(speed))
map_ci
```

### All SBARC AIS data off of LA and OC for 1-2 June 2019

```{r, echo=FALSE, message=FALSE, warning=FALSE}
sbais062019<-readRDS("data/sbais062019.RDS") %>% 
  filter(lon >= -118.795374 & lon <= -117.707252,
         lat >= 33.080975 & lat <= 33.680974)%>%
  arrange(datetime) %>%
  st_as_sf(coords=c("lon","lat"), crs = 4326)

bins_ci <- c(0,10,11,12,15,20)

pal_sbais062019 <- colorBin( "YlOrRd",
                    domain= sbais062019$speed,
                    bins = bins_ci,
                    na.color = 'black')

map_sbais062019 <- leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data=sbais062019,
                   radius = 0.5,
                   label = ~sprintf("%f knots - %s %s",speed,datetime,name),
                   color=~pal_sbais062019(speed))
map_sbais062019

```


